'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ITSP_CDA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;!-- filename=adlcp_rootv1p2.xsd --&gt;
        '''&lt;!-- Conforms to w3c http://www.w3.org/TR/xmlschema-1/ 2000-10-24--&gt;
        '''
        '''&lt;xsd:schema xmlns=&quot;http://www.adlnet.org/xsd/adlcp_rootv1p2&quot;
        '''            targetNamespace=&quot;http://www.adlnet.org/xsd/adlcp_rootv1p2&quot;
        '''            xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        '''            xmlns:imscp=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot;
        '''            xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''            elementFormDefault=&quot;unqualified&quot;
        '''      [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property adlcp_rootv1p2() As String
            Get
                Return ResourceManager.GetString("adlcp_rootv1p2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .animate-arrow {
        '''    
        '''}
        '''.arrow-slide-right{
        '''  animation: slideRight ease 0.8s;
        '''  -webkit-animation: slideRight ease 0.8s;
        '''  -moz-animation: slideRight ease 0.8s;
        '''  -o-animation: slideRight ease 0.8s;
        '''  -ms-animation: slideRight ease 0.8s;
        '''  animation-iteration-count: infinite;
        '''  transform-origin: 50% 50%;
        '''  -webkit-animation-iteration-count: infinite;
        '''  -webkit-transform-origin: 50% 50%;
        '''   -moz-animation-iteration-count: infinite;
        '''  -moz-transform-origin: 50% 50%;
        '''   -o-animation-iteration-c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property animation() As String
            Get
                Return ResourceManager.GetString("animation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*******************************************************************************
        '''**
        '''** FileName: APIWrapper.js
        '''**
        '''*******************************************************************************/
        '''
        '''/*******************************************************************************
        '''**
        '''** Concurrent Technologies Corporation (CTC) grants you (&quot;Licensee&quot;) a non-
        '''** exclusive, royalty free, license to use, modify and redistribute this
        '''** software in source and binary code form, provided that i) this copyrig [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property APIWrapper() As String
            Get
                Return ResourceManager.GetString("APIWrapper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow_Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow_Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow_Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow_Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow_Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''
        '''&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;Digital Learning Solutions - Assessment Outcome&lt;/title&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; href=&quot;css/jquery_ui.css&quot; /&gt;
        '''    &lt;link href=&quot;css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;script src=&quot;js/jquery.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;js/jquery_ui.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;js/crosshair-min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;style&gt;
        '''        .hidden{
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AssessOutcome() As String
            Get
                Return ResourceManager.GetString("AssessOutcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Back_F1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back_F1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Back_F2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back_F2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blank_thmb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_thmb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],template{display:none}a{background-color:transparent}a:active,a:hover{outline:0}abbr[title]{border-bottom:1px dotted}b,strong{font-weight:bold}dfn{font-style:italic}h1{margin:.67em 0; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bootstrap_min_css() As String
            Get
                Return ResourceManager.GetString("bootstrap_min_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        ''' * Bootstrap v3.3.2 (http://getbootstrap.com)
        ''' * Copyright 2011-2015 Twitter, Inc.
        ''' * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        ''' */
        '''if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;var b=a.fn.jquery.split(&quot; &quot;)[0].split(&quot;.&quot;);if(b[0]&lt;2&amp;&amp;b[1]&lt;9||1==b[0]&amp;&amp;9==b[1]&amp;&amp;b[2]&lt;1)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery version 1.9.1 or higher&quot;)}(jQuery),+function(a){&quot;use strict&quot;;function b(){var a=docume [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bootstrap_min_js() As String
            Get
                Return ResourceManager.GetString("bootstrap_min_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        ''' *  crosshair.js - v0.1.0
        ''' *  Crosshair any dom element.
        ''' *  https://github.com/eschmar/crosshair
        ''' *
        ''' *  @author:   Marcel Eschmann, @eschmar
        ''' *  @license:  MIT License
        ''' */
        ''';
        '''(function (e, i, t, s) {
        '''    var r, n, h, o, a, l, c = {
        '''        scale: 1,
        '''        wrap: true,
        '''        legend: true,
        '''        marker: &apos;&apos;,
        '''        callback: function (e) {
        '''            console.log(e.pct)
        '''        }
        '''    };
        '''
        '''    function d(i, t) {
        '''        this.options = e.extend({}, c, t);
        '''        this._defaults = c; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property crosshair_min() As String
            Get
                Return ResourceManager.GetString("crosshair_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;Digital Learning Solutions - Diagnostic Assessment Outcome&lt;/title&gt;
        '''       &lt;link rel=&quot;stylesheet&quot; href=&quot;css/jquery_ui.css&quot;/&gt;
        '''    &lt;link href=&quot;css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;script src=&quot;js/jquery.js&quot;&gt;&lt;/script&gt;
        '''  &lt;script src=&quot;js/jquery_ui.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;js/crosshair-min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DiagnosticOutcome() As String
            Get
                Return ResourceManager.GetString("DiagnosticOutcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to history.pushState(null, null, document.title);
        '''window.addEventListener(&apos;popstate&apos;, function () {
        '''    history.pushState(null, null, document.title);
        '''});.
        '''</summary>
        Friend ReadOnly Property disable_back_nav_script() As String
            Get
                Return ResourceManager.GetString("disable_back_nav_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exit_f1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_f1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exit_f2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_f2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HighlightBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HighlightBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;        '''&lt;!-- filename=ims_xml.xsd --&gt;        '''&lt;xsd:schema xmlns=&quot;http://www.w3.org/XML/1998/namespace&quot;         '''            targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot;         '''            xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;         '''            elementFormDefault=&quot;qualified&quot;&gt;        '''	&lt;!-- 2001-02-22 edited by Thomas Wason IMS Global Learning Consortium, Inc. --&gt;        '''	&lt;xsd:annotation&gt;        '''		&lt;xsd:documentation&gt;In namespace-aware XML processors, the &amp;quot;xml&amp;quot; prefix is bound to the namespace name ht [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ims_xml() As String
            Get
                Return ResourceManager.GetString("ims_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''
        '''&lt;!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Thomas Wason (private) --&gt;
        '''&lt;!-- filename=ims_cp_rootv1p1p2.xsd --&gt;
        '''&lt;!-- Copyright (2) 2001 IMS Global Learning Consortium, Inc. --&gt;
        '''&lt;!-- edited by Thomas Wason  --&gt;
        '''&lt;!-- Conforms to w3c http://www.w3.org/TR/xmlschema-1/ 2000-10-24--&gt;
        '''
        '''&lt;xsd:schema xmlns=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot; 
        '''            targetNamespace=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot; 
        '''            xmlns:xml=&quot;http://www.w3.org/ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property imscp_rootv1p1p2() As String
            Get
                Return ResourceManager.GetString("imscp_rootv1p1p2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;manifest identifier=&quot;_5Ul3QJs6ODJ_course_id&quot; version=&quot;1.0&quot; xmlns=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot; xmlns:adlcp=&quot;http://www.adlnet.org/xsd/adlcp_rootv1p2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd&quot;&gt;
        '''  &lt;metadata&gt;
        '''    &lt;schema&gt;ADL  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property imsmanifest() As String
            Get
                Return ResourceManager.GetString("imsmanifest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;!-- edited by Thomas Wason  --&gt;
        '''&lt;xsd:schema targetNamespace=&quot;http://www.imsglobal.org/xsd/imsmd_rootv1p2p1&quot; 
        '''            xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot; 
        '''            xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        '''            xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        '''            xmlns=&quot;http://www.imsglobal.org/xsd/imsmd_rootv1p2p1&quot; 
        '''            elementFormDefault=&quot;qualified&quot; 
        '''            version=&quot;1.2:1.1 IMS:MD1.2&quot;&gt;
        '''
        '''   &lt;xsd:impor [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property imsmd_rootv1p2p1() As String
            Get
                Return ResourceManager.GetString("imsmd_rootv1p2p1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //Handle assessment outcome:
        '''var qs = &apos;&apos;;
        '''var vSelectionStart = -10;
        '''var vSelectionEnd = -10;
        '''function AssessmentOutcome(correct, tutid) {
        '''    if (isPreview === true) {
        '''        window.status = window.status.replace(&apos;Assessment outcome: CORRECT&apos;, &apos;&apos;);
        '''        window.status = window.status.replace(&apos;Assessment outcome: INCORRECT&apos;, &apos;&apos;);
        '''        if (correct) {
        '''            window.status = window.status + &apos;Assessment outcome: CORRECT&apos;;
        '''            qs = &apos;?outcome=1&apos;;
        '''        }
        '''        else {
        '''           [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property itsp_content() As String
            Get
                Return ResourceManager.GetString("itsp_content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to var fixedtime = &quot;0&quot;;
        '''var iscomplete = false;
        '''var startDate = new Date().getTime();
        '''; (function ($) {
        '''    $.preload = function () {
        '''        var imgs = Object.prototype.toString.call(arguments[0]) === &apos;[object Array]&apos;
        '''          ? arguments[0] : arguments;
        '''
        '''        var tmp = [];
        '''        var i = imgs.length;
        '''
        '''        // reverse loop run faster
        '''        for (; i-- ;) tmp.push($(&apos;&lt;img /&gt;&apos;).attr(&apos;src&apos;, imgs[i]));
        '''    };
        '''})(jQuery);
        '''
        '''function getp(name) {
        '''    return decodeURIComponent((new RegExp(&apos;[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property itsp_tracking() As String
            Get
                Return ResourceManager.GetString("itsp_tracking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to var fixedtime = &quot;0&quot;;
        '''var ContentType = &quot;XXContentTypeXX&quot;;
        '''var PLAThresh = 123456789;
        '''var iscomplete = false;
        '''var startDate = new Date().getTime();
        '''; (function ($) {
        '''
        '''    $.preload = function () {
        '''        var imgs = Object.prototype.toString.call(arguments[0]) === &apos;[object Array]&apos;
        '''          ? arguments[0] : arguments;
        '''
        '''        var tmp = [];
        '''        var i = imgs.length;
        '''
        '''        // reverse loop run faster
        '''        for (; i-- ;) tmp.push($(&apos;&lt;img /&gt;&apos;).attr(&apos;src&apos;, imgs[i]));
        '''    };
        '''})(jQuery);
        '''        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property itsp_tracking_sco() As String
            Get
                Return ResourceManager.GetString("itsp_tracking_sco", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to html, body {
        '''    font: 1em Calibri;
        '''    margin: 0;
        '''    padding: 0;
        '''    width: 100%;
        '''    height: 100%;
        '''    display: table;
        '''}
        '''/*body:before {
        '''    content: url(/MOST_PowerPoint10_4_01_03_html/images/screen01.png) url(/MOST_PowerPoint10_4_01_03_html/navimages/blank.png) url(/MOST_PowerPoint10_4_01_03_html/images/fileButton_F2.png) url(/MOST_PowerPoint10_4_01_03_html/images/Arrow.png) url(/MOST_PowerPoint10_4_01_03_html/images/screen02.png) url(/MOST_PowerPoint10_4_01_03_html/images/pptoptF2.png) url(/M [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property itsplearning() As String
            Get
                Return ResourceManager.GetString("itsplearning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itsplogo_sm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itsplogo_sm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''
        '''&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;Digital Learning Solutions Content Player&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''		* { margin: 0px; }
        '''                html, body, iframe { height:100%; }
        '''		html, body { overflow-y:hidden; font-family:Helvetica, &quot;Helvetica Neue&quot;, Arial; font-size:12px; }
        '''		iframe { display:block; width:100%; }
        '''
        '''		html, body, iframe , a, img, table, tbody, tr, td, table td, table th {
        '''		 border : 0px [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property itspplayer() As String
            Get
                Return ResourceManager.GetString("itspplayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''
        '''&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;Digital Learning Solutions Content Player&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''		* { margin: 0px; }
        '''                html, body, iframe { height:100%; }
        '''		html, body { overflow-y:hidden; font-family:Helvetica, &quot;Helvetica Neue&quot;, Arial; font-size:12px; }
        '''		iframe { display:block; width:100%; }
        '''
        '''		html, body, iframe , a, img, table, tbody, tr, td, table td, table th {
        '''		 border : 0px [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property itspplayer_sco() As String
            Get
                Return ResourceManager.GetString("itspplayer_sco", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery v1.12.0 | (c) jQuery Foundation | jquery.org/license */
        '''!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m=&quot;1.12.0&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[\s\uFEFF\xA0]+| [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery() As String
            Get
                Return ResourceManager.GetString("jquery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery UI - v1.11.4 - 2016-01-12
        '''* http://jqueryui.com
        '''* Includes: core.css, draggable.css, resizable.css, selectable.css, sortable.css
        '''* Copyright jQuery Foundation and other contributors; Licensed MIT */
        '''
        '''.ui-helper-hidden{display:none}.ui-helper-hidden-accessible{border:0;clip:rect(0 0 0 0);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px}.ui-helper-reset{margin:0;padding:0;border:0;outline:0;line-height:1.3;text-decoration:none;font-size:100%;list-style:none}.ui-helper-cl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_css() As String
            Get
                Return ResourceManager.GetString("jquery_ui_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery UI - v1.11.4 - 2016-01-12
        '''* http://jqueryui.com
        '''* Includes: core.js, widget.js, mouse.js, position.js, draggable.js, droppable.js, resizable.js, selectable.js, sortable.js, effect.js, effect-bounce.js, effect-clip.js, effect-fade.js, effect-highlight.js, effect-puff.js, effect-pulsate.js, effect-scale.js, effect-size.js, effect-slide.js, effect-transfer.js
        '''* Copyright jQuery Foundation and other contributors; Licensed MIT */
        '''
        '''(function(e){&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],e) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_js() As String
            Get
                Return ResourceManager.GetString("jquery_ui_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;lom xmlns=&quot;http://www.imsglobal.org/xsd/imsmd_rootv1p2p1&quot;
        '''     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        '''	 xmlns:pkgprop=&quot;http://www.scorm.com/xsd/ScormEnginePackageProperties&quot;
        '''     xsi:schemaLocation=&quot;http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd 
        '''	 http://www.scorm.com/xsd/ScormEnginePackageProperties ScormEnginePackageProperties.xsd&quot;&gt;
        '''
        '''    &lt;general&gt;
        '''        
        '''        &lt;title&gt;
        '''            &lt;langstring&gt;XXXCourseTitleXXX&lt;/langstring&gt;
        '''        &lt;/ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property metadata() As String
            Get
                Return ResourceManager.GetString("metadata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Next_F1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_F1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Next_F2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_F2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pass_f2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pass_f2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paste_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paste_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to var $el = $(&quot;#content&quot;);
        '''var elHeight = $el.outerHeight();
        '''var elWidth = $el.outerWidth();
        '''
        '''var $wrapper = $(&quot;#scaleable-wrapper&quot;);
        '''
        '''//$wrapper.resizable({
        '''//    resize: doResize
        '''//});
        '''var scale;
        '''function doResize(event, uheight, uwidth) {
        '''    $wrapper.css({ width: uwidth + &quot;px&quot;, height: uheight + &quot;px&quot; });
        '''    scale = Math.min(
        '''        uwidth / elWidth,
        '''        uheight / elHeight
        '''    );
        '''
        '''    $el.css({
        '''        transform: &quot;translate(-50%, -50%) &quot; + &quot;scale(&quot; + scale + &quot;)&quot;
        '''    });
        '''
        '''}
        '''windo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property player_scaling() As String
            Get
                Return ResourceManager.GetString("player_scaling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        '''    &lt;title&gt;DLS Learning Materials&lt;/title&gt;
        '''    &lt;link href=&quot;XXitsplearningcssXX&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;link href=&quot;XXanimationcssXX&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; href=&quot;XXjquery_ui_cssXX&quot;/&gt;
        '''    &lt;link href=&quot;XXbootstrapcssXX&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;script src=&quot;XXjquery_jsXX&quot;&gt;&lt;/script&gt;
        '''  &lt;script src=&quot;XXjquery_ui_jsXX&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;XXcrosshair-minXX&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;X [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PreviewPage() As String
            Get
                Return ResourceManager.GetString("PreviewPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div id=&apos;quiz-content&apos; role=&apos;presentation&apos; class=&apos;col-sm-10 col-sm-offset-1&apos; style=&apos;position: absolute; margin-top: 10%;&apos;&gt;
        '''            &lt;div class=&apos;well&apos; role=&apos;presentation&apos; style=&apos;max-height: 580px;overflow: auto;-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-webkit-box-shadow:0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);box-shadow:0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);&apos;&gt;
        '''                &lt;div id=&apos;qhead&apos; class=&apos;h4&apos; style=&apos;fo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property quiz_question() As String
            Get
                Return ResourceManager.GetString("quiz_question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to var startDate;
        '''var exitPageStatus;
        '''
        '''function loadPage()
        '''{
        '''   var result = doLMSInitialize();
        '''
        '''   var status = doLMSGetValue( &quot;cmi.core.lesson_status&quot; );
        '''
        '''   if (status == &quot;not attempted&quot;)
        '''   {
        '''	  // the student is now attempting the lesson
        '''	  doLMSSetValue( &quot;cmi.core.lesson_status&quot;, &quot;incomplete&quot; );
        '''   }
        '''
        '''   exitPageStatus = false;
        '''   startTimer();
        '''}
        '''
        '''
        '''function startTimer()
        '''{
        '''   startDate = new Date().getTime();
        '''}
        '''
        '''function computeTime()
        '''{
        '''   if ( startDate != 0 )
        '''   {
        '''      var  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SCOFunctions() As String
            Get
                Return ResourceManager.GetString("SCOFunctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!– saved from url=(0014)about:internet –&gt; 
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        '''    &lt;title&gt;DLS Learning Materials&lt;/title&gt;
        '''    &lt;link href=&quot;XXitsplearningcssXX&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;link href=&quot;XXanimationcssXX&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;link href=&quot;XXbootstrapcssXX&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; href=&quot;XXjquery_ui_cssXX&quot;/&gt;
        '''
        '''    &lt;script src=&quot;XXjquery_jsXX&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;XXjquery_ui_jsXX&quot;&gt;&lt;/script&gt;
        '''    &lt;script src= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ViewPage() As String
            Get
                Return ResourceManager.GetString("ViewPage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
