'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>  _
Partial Friend NotInheritable Class cdasettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As cdasettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New cdasettings()),cdasettings)
    
    Public Shared ReadOnly Property [Default]() As cdasettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    '''<summary>
    '''User defined path to image editor executable
    '''</summary>
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Configuration.SettingsDescriptionAttribute("User defined path to image editor executable"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ImageEditor() As String
        Get
            Return CType(Me("ImageEditor"),String)
        End Get
        Set
            Me("ImageEditor") = value
        End Set
    End Property
End Class
